### ISSUE TITLE
colab pro

### ISSUE THREAD

**Issue by liillloooo** [gist-ailab/teaching-where-to-look#15]
Hello;
Thank you for your amazing job!
Can I run this code on google colab pro? If so, what changes should I done to have the outputs?
Thank you in advance.

**Comment by tjdhg456** [comment]
Hi. Thank you for your interest.
I do not have experience with colab, so I cannot provide any supports.
But, our code work in linux OS, so it'll work in the colab platform if it provides linux-based environments.
