### ISSUE TITLE
how to get agedb_30_pair.txt

### ISSUE THREAD

**Issue by ohtiger** [gist-ailab/teaching-where-to-look#2]
could you tell me  what to do with AgeDB dataset, and how to get get agedb_30_pair.txt?

**Comment by tjdhg456** [comment]
Hi! you can download the aligned CASIA and AgeDB30 dataset from here (https://github.com/deepinsight/insightface/tree/master/recognition/_datasets_)

We also update the detailed process about generating image dataset from the bin files in the ReadME.
