### ISSUE TITLE
the webface_align_112 dataset and webface_align_train.list

### ISSUE THREAD

**Issue by ohtiger** [gist-ailab/teaching-where-to-look#4]
Thanks for your job, and could you give me the webface_align_112 dataset and webface_align_train.list
Thank you!

**Comment by tjdhg456** [comment]
Hi! you can download the aligned CASIA and AgeDB30 dataset from here (https://github.com/deepinsight/insightface/tree/master/recognition/_datasets_)

Also, using the "utils/load_images_from_bin.py", you can load the images from the bin formatted files.
