### ISSUE TITLE
scripts

### ISSUE THREAD

**Issue by lilydablue** [gist-ailab/teaching-where-to-look#5]
hello,
I really appreciate what you have done.
excuse me, how can I have the train scripts?

I used default values in your code:

!python /content/teaching-where-to-look/train_teacher.py --save_dir /content/checkpoints --down_size 28 --total_iters 47000 --batch_size 256 --gpus 1 --data_dir /content/Face

 but I cannot run it.

thank you in advance

**Comment by tjdhg456** [comment]
Hello!
I updated the example training scripts in the $scripts/ folder.

If you get some errors, can you upload the snippet?

Thank you for your interest.

**Comment by lilydablue** [comment]
thank you for your attention!

after data preparation, I ran this script below and still get error:

!python /content/teaching-where-to-look/train_teacher.py --gpus 0 --save_dir /content/checkpoint/teacher --down_size 112 --batch_size 256 --data_dir /content/Face


 
<img width="932" alt="Untitled" src="https://user-images.githubusercontent.com/83751895/213784091-485b5c78-57c5-46d8-b00e-5c1b35ce34d1.png">

**Comment by tjdhg456** [comment]
Hi! 

The error means out of memory problem.

You need to use more gpu or reduce the batch size to reduce the memory (it will require more training time).
