### ISSUE TITLE
SyntaxError: 'yield' inside list comprehension

### ISSUE THREAD

**Issue by UmbrellaOffRain** [gist-ailab/teaching-where-to-look#7]
I try the python3.7 rather than python3.8 as the requestment.txt, which avoid the bug totally.

**Comment by tjdhg456** [comment]
Hello! 

Thank you for your interest.

Did you solved the problems?
Or any other bugs need to be solved?

**Comment by UmbrellaOffRain** [comment]
I'm surprised to hear from you so soon, thank you very much!


Yep, I have done！ It works well on python3.7.&nbsp;
Your note request python3.8, but we know the problem cause by the version 3.8+, which may need correction.


By the way,&nbsp;I have a puzzle that I hope to get your answer, please.
I want to&nbsp;realize your demo now. But I don't know several details yet. What kinds of your training set in your demo when you need to face&nbsp;identification？ Do you used the Gallery set only or using the&nbsp;TinyFace dataset with&nbsp;Gallery set?
What's more, may&nbsp;I share the demo code, please?







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gist-ailab/teaching-where-to-look"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月3日(星期五) 上午10:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gist-ailab/teaching-where-to-look] SyntaxError: 'yield' inside list comprehension (Issue #7)





 
Hello!
 
Thank you for your interest.
 
Did you solved the problems?
 Or any other bugs need to be solved?

**Comment by tjdhg456** [comment]
Hi!

Sorry for the inconvenience.
I'll revise the readme.md (python 3.8 -> 3.7).

To construct the demo, I utilized the Son's (famous soccer player from Korea) video downloaded from the youtube.
Also, the gallery images are downloaded from the Google (other soccer players).
