### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:2 and cuda:1!

### ISSUE THREAD

**Issue by zhaisc2001** [gist-ailab/teaching-where-to-look#8]
hi there,
thanks for your job, i run train_teacher.py without any error, but when i run train_student.py on 4 gpus, i got an error as:
![image](https://user-images.githubusercontent.com/43377772/218294340-05928a98-2e74-4c38-92a8-042b3ced4114.png)

do you guys have any idea about how to fix it right? Thank you!

**Comment by tjdhg456** [comment]
Sorry for the inconvenience.
I'm now on a business trip, so I'll check this problem in next week!

**Comment by lilydablue** [comment]
hello
I have the same problem here!
thank you

**Comment by guzejungithub** [comment]
the same question

**Comment by tjdhg456** [comment]
Fixed the error!
Sorry for the delay.
