### ISSUE TITLE
what's hook for?

### ISSUE THREAD

**Issue by ohtiger** [gist-ailab/teaching-where-to-look#9]
sir, could you tell me the hook function is for what, my code ability is a little poor.

**Comment by tjdhg456** [comment]
Hi!
Hook is an utility function to extract feature (forward pass) or gradient (backward pass) from target layer inside a network. You can designate target layer by setting class name.

In this paper, we utilized a forward hook to extract attention features from CBAM module.

Hope this commenrs will be helpful.
If you have any more question, feel free to ask!
